# Generated by Django 3.1.4 on 2021-02-11 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(blank=True, null=True, upload_to='', verbose_name='Загрузка файла')),
            ],
            options={
                'verbose_name': 'Загрузка файла',
                'verbose_name_plural': 'Загрузка файлов',
            },
        ),
        migrations.CreateModel(
            name='TableAndUrlColumns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(blank=True, default='', max_length=255, verbose_name='Организация')),
                ('material_assigning', models.CharField(blank=True, default='', max_length=255, verbose_name='Назначение материала')),
                ('account_purpose', models.CharField(blank=True, default='', max_length=255, verbose_name='Назначение счёта')),
                ('contract_number', models.CharField(blank=True, default='', max_length=255, verbose_name='№ договора')),
                ('contract_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Сумма по договору')),
                ('paid1', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Оплачено')),
                ('account_number', models.CharField(blank=True, default='', max_length=255, verbose_name='№ счёта')),
                ('account_date', models.DateField(blank=True, null=True, verbose_name='Дата счёта')),
                ('accounts_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Сумма по счётам')),
                ('for_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='В оплату')),
                ('payment_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Остаток по оплате')),
                ('paid2', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Оплачено')),
                ('remainder', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Остаток')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Примечание')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Сумма-1')),
                ('docfile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LoadPayRegsApp.docfile', verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Запись с реестра',
                'verbose_name_plural': 'Записи с реестра',
                'ordering': ['organization'],
            },
        ),
    ]
